site: Forest Miller CPA

url: https://meredithmclendon.github.io
baseurl: /forestmillercpa

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /resources/:slug
  projects:
    output: true
    permalink: /projects/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/resources/page:num/"
  